name: Deploy ML Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: saibatttula93/regression-app:latest
          # Replace 'your-docker-registry/your-image-name' with your actual Docker image repository and image name

      # Add any additional steps you may need for your specific deployment environment,
      # such as deploying to a cloud service like AWS ECS, GCP GKE, or Azure AKS.
