name: Deploy ML Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_TAG: latest  # Define the Docker image tag here (modify as needed)

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Build the Docker image
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .  # The context for Docker build (location of Dockerfile and application code)
          push: true   # Set to "true" to push the image to a container registry
          tags: your-docker-registry/regression_app:${de52fa633bf0}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          # Add any other environment variables required for the image build, if applicable

      # Step 3: Run the Docker container
      - name: Run Docker Container
        run: docker run -d -p 8000:8000 your-docker-registry/regression_app:${de52fa633bf0}

      # Step 4: Check if the application is running
      - name: Wait for Application
        run: |
          while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8000)" != "200" ]]; do
            sleep 5
          done
        timeout-minutes: 5  # Adjust the timeout as per your application's startup time

#Sai Durga Prasad
